INSERT INTO equipos (id, nombre, pais, bandera_url) VALUES
(1, 'Afganistán', 'Afganistán', 'https://flagpedia.net/data/flags/h80/af.png'),
(2, 'Albania', 'Albania', 'https://flagpedia.net/data/flags/h80/al.png'),
(3, 'Alemania', 'Alemania', 'https://flagpedia.net/data/flags/h80/de.png'),
(4, 'Andorra', 'Andorra', 'https://flagpedia.net/data/flags/h80/ad.png'),
(5, 'Angola', 'Angola', 'https://flagpedia.net/data/flags/h80/ao.png'),
(6, 'Antigua y Barbuda', 'Antigua y Barbuda', 'https://flagpedia.net/data/flags/h80/ag.png'),
(7, 'Arabia Saudita', 'Arabia Saudita', 'https://flagpedia.net/data/flags/h80/sa.png'),
(8, 'Argelia', 'Argelia', 'https://flagpedia.net/data/flags/h80/dz.png'),
(9, 'Argentina', 'Argentina', 'https://flagpedia.net/data/flags/h80/ar.png'),
(10, 'Armenia', 'Armenia', 'https://flagpedia.net/data/flags/h80/am.png'),
(11, 'Australia', 'Australia', 'https://flagpedia.net/data/flags/h80/au.png'),
(12, 'Austria', 'Austria', 'https://flagpedia.net/data/flags/h80/at.png'),
(13, 'Azerbaiyán', 'Azerbaiyán', 'https://flagpedia.net/data/flags/h80/az.png'),
(14, 'Bahamas', 'Bahamas', 'https://flagpedia.net/data/flags/h80/bs.png'),
(15, 'Bahréin', 'Bahréin', 'https://flagpedia.net/data/flags/h80/bh.png'),
(16, 'Bangladés', 'Bangladés', 'https://flagpedia.net/data/flags/h80/bd.png'),
(17, 'Barbados', 'Barbados', 'https://flagpedia.net/data/flags/h80/bb.png'),
(18, 'Bélgica', 'Bélgica', 'https://flagpedia.net/data/flags/h80/be.png'),
(19, 'Belice', 'Belice', 'https://flagpedia.net/data/flags/h80/bz.png'),
(20, 'Benín', 'Benín', 'https://flagpedia.net/data/flags/h80/bj.png'),
(21, 'Bielorrusia', 'Bielorrusia', 'https://flagpedia.net/data/flags/h80/by.png'),
(22, 'Birmania', 'Birmania', 'https://flagpedia.net/data/flags/h80/mm.png'),
(23, 'Bosnia y Herzegovina', 'Bosnia y Herzegovina', 'https://flagpedia.net/data/flags/h80/ba.png'),
(24, 'Botsuana', 'Botsuana', 'https://flagpedia.net/data/flags/h80/bw.png'),
(25, 'Brasil', 'Brasil', 'https://flagpedia.net/data/flags/h80/br.png'),
(26, 'Brunéi', 'Brunéi', 'https://flagpedia.net/data/flags/h80/bn.png'),
(27, 'Bulgaria', 'Bulgaria', 'https://flagpedia.net/data/flags/h80/bg.png'),
(28, 'Burkina Faso', 'Burkina Faso', 'https://flagpedia.net/data/flags/h80/bf.png'),
(29, 'Burundi', 'Burundi', 'https://flagpedia.net/data/flags/h80/bi.png'),
(30, 'Bután', 'Bután', 'https://flagpedia.net/data/flags/h80/bt.png'),
(31, 'Cabo Verde', 'Cabo Verde', 'https://flagpedia.net/data/flags/h80/cv.png'),
(32, 'Camboya', 'Camboya', 'https://flagpedia.net/data/flags/h80/kh.png'),
(33, 'Camerún', 'Camerún', 'https://flagpedia.net/data/flags/h80/cm.png'),
(34, 'Canadá', 'Canadá', 'https://flagpedia.net/data/flags/h80/ca.png'),
(35, 'Catar', 'Catar', 'https://flagpedia.net/data/flags/h80/qa.png'),
(36, 'Chad', 'Chad', 'https://flagpedia.net/data/flags/h80/td.png'),
(37, 'Chile', 'Chile', 'https://flagpedia.net/data/flags/h80/cl.png'),
(38, 'China', 'China', 'https://flagpedia.net/data/flags/h80/cn.png'),
(39, 'Chipre', 'Chipre', 'https://flagpedia.net/data/flags/h80/cy.png'),
(40, 'Colombia', 'Colombia', 'https://flagpedia.net/data/flags/h80/co.png'),
(41, 'Comoras', 'Comoras', 'https://flagpedia.net/data/flags/h80/km.png'),
(42, 'Congo', 'Congo', 'https://flagpedia.net/data/flags/h80/cg.png'),
(43, 'Congo (República Democrática del Congo)', 'Congo (República Democrática del Congo)', 'https://flagpedia.net/data/flags/h80/cd.png'),
(44, 'Corea del Norte', 'Corea del Norte', 'https://flagpedia.net/data/flags/h80/kp.png'),
(45, 'Corea del Sur', 'Corea del Sur', 'https://flagpedia.net/data/flags/h80/kr.png'),
(46, 'Costa de Marfil', 'Costa de Marfil', 'https://flagpedia.net/data/flags/h80/ci.png'),
(47, 'Costa Rica', 'Costa Rica', 'https://flagpedia.net/data/flags/h80/cr.png'),
(48, 'Croacia', 'Croacia', 'https://flagpedia.net/data/flags/h80/hr.png'),
(49, 'Cuba', 'Cuba', 'https://flagpedia.net/data/flags/h80/cu.png'),
(50, 'Curazao', 'Curazao', 'https://flagpedia.net/data/flags/h80/cw.png');
INSERT INTO equipos (id, nombre, pais, bandera_url) VALUES
(51, 'Dinamarca', 'Dinamarca', 'https://flagpedia.net/data/flags/h80/dk.png'),
(52, 'Dominica', 'Dominica', 'https://flagpedia.net/data/flags/h80/dm.png'),
(53, 'Ecuador', 'Ecuador', 'https://flagpedia.net/data/flags/h80/ec.png'),
(54, 'Egipto', 'Egipto', 'https://flagpedia.net/data/flags/h80/eg.png'),
(55, 'El Salvador', 'El Salvador', 'https://flagpedia.net/data/flags/h80/sv.png'),
(56, 'Emiratos Árabes Unidos', 'Emiratos Árabes Unidos', 'https://flagpedia.net/data/flags/h80/ae.png'),
(57, 'Eslovaquia', 'Eslovaquia', 'https://flagpedia.net/data/flags/h80/sk.png'),
(58, 'Eslovenia', 'Eslovenia', 'https://flagpedia.net/data/flags/h80/si.png'),
(59, 'España', 'España', 'https://flagpedia.net/data/flags/h80/es.png'),
(60, 'Estados Unidos', 'Estados Unidos', 'https://flagpedia.net/data/flags/h80/us.png'),
(61, 'Estonia', 'Estonia', 'https://flagpedia.net/data/flags/h80/ee.png'),
(62, 'Esuatini', 'Esuatini', 'https://flagpedia.net/data/flags/h80/sz.png'),
(63, 'Etiopía', 'Etiopía', 'https://flagpedia.net/data/flags/h80/et.png'),
(64, 'Fiji', 'Fiji', 'https://flagpedia.net/data/flags/h80/fj.png'),
(65, 'Filipinas', 'Filipinas', 'https://flagpedia.net/data/flags/h80/ph.png'),
(66, 'Finlandia', 'Finlandia', 'https://flagpedia.net/data/flags/h80/fi.png'),
(67, 'Francia', 'Francia', 'https://flagpedia.net/data/flags/h80/fr.png'),
(68, 'Gabón', 'Gabón', 'https://flagpedia.net/data/flags/h80/ga.png'),
(69, 'Gambia', 'Gambia', 'https://flagpedia.net/data/flags/h80/gm.png'),
(70, 'Georgia', 'Georgia', 'https://flagpedia.net/data/flags/h80/ge.png'),
(71, 'Ghana', 'Ghana', 'https://flagpedia.net/data/flags/h80/gh.png'),
(72, 'Granada', 'Granada', 'https://flagpedia.net/data/flags/h80/gd.png'),
(73, 'Grecia', 'Grecia', 'https://flagpedia.net/data/flags/h80/gr.png'),
(74, 'Guatemala', 'Guatemala', 'https://flagpedia.net/data/flags/h80/gt.png'),
(75, 'Guinea', 'Guinea', 'https://flagpedia.net/data/flags/h80/gn.png'),
(76, 'Guinea-Bisáu', 'Guinea-Bisáu', 'https://flagpedia.net/data/flags/h80/gw.png'),
(77, 'Guyana', 'Guyana', 'https://flagpedia.net/data/flags/h80/gy.png'),
(78, 'Haití', 'Haití', 'https://flagpedia.net/data/flags/h80/ht.png'),
(79, 'Honduras', 'Honduras', 'https://flagpedia.net/data/flags/h80/hn.png'),
(80, 'Hungría', 'Hungría', 'https://flagpedia.net/data/flags/h80/hu.png'),
(81, 'India', 'India', 'https://flagpedia.net/data/flags/h80/in.png'),
(82, 'Indonésia', 'Indonésia', 'https://flagpedia.net/data/flags/h80/id.png'),
(83, 'Irak', 'Irak', 'https://flagpedia.net/data/flags/h80/iq.png'),
(84, 'Irlanda', 'Irlanda', 'https://flagpedia.net/data/flags/h80/ie.png'),
(85, 'Islas Caimán', 'Islas Caimán', 'https://flagpedia.net/data/flags/h80/ky.png'),
(86, 'Islas Cook', 'Islas Cook', 'https://flagpedia.net/data/flags/h80/ck.png'),
(87, 'Islas Marshall', 'Islas Marshall', 'https://flagpedia.net/data/flags/h80/mh.png'),
(88, 'Islas Salomón', 'Islas Salomón', 'https://flagpedia.net/data/flags/h80/sb.png'),
(89, 'Islas Vírgenes Británicas', 'Islas Vírgenes Británicas', 'https://flagpedia.net/data/flags/h80/vg.png'),
(90, 'Israel', 'Israel', 'https://flagpedia.net/data/flags/h80/il.png'),
(91, 'Italia', 'Italia', 'https://flagpedia.net/data/flags/h80/it.png'),
(92, 'Jamaica', 'Jamaica', 'https://flagpedia.net/data/flags/h80/jm.png'),
(93, 'Japón', 'Japón', 'https://flagpedia.net/data/flags/h80/jp.png'),
(94, 'Jordania', 'Jordania', 'https://flagpedia.net/data/flags/h80/jo.png'),
(95, 'Kazajistán', 'Kazajistán', 'https://flagpedia.net/data/flags/h80/kz.png'),
(96, 'Kenia', 'Kenia', 'https://flagpedia.net/data/flags/h80/ke.png'),
(97, 'Kirguistán', 'Kirguistán', 'https://flagpedia.net/data/flags/h80/kg.png'),
(98, 'Kiribati', 'Kiribati', 'https://flagpedia.net/data/flags/h80/ki.png'),
(99, 'Kuwait', 'Kuwait', 'https://flagpedia.net/data/flags/h80/kw.png'),
(100, 'Laos', 'Laos', 'https://flagpedia.net/data/flags/h80/la.png');
INSERT INTO equipos (id, nombre, pais, bandera_url) VALUES
(101, 'Lesoto', 'Lesoto', 'https://flagpedia.net/data/flags/h80/ls.png'),
(102, 'Letonia', 'Letonia', 'https://flagpedia.net/data/flags/h80/lv.png'),
(103, 'Líbano', 'Líbano', 'https://flagpedia.net/data/flags/h80/lb.png'),
(104, 'Liberia', 'Liberia', 'https://flagpedia.net/data/flags/h80/lr.png'),
(105, 'Libia', 'Libia', 'https://flagpedia.net/data/flags/h80/ly.png'),
(106, 'Liechtenstein', 'Liechtenstein', 'https://flagpedia.net/data/flags/h80/li.png'),
(107, 'Lituania', 'Lituania', 'https://flagpedia.net/data/flags/h80/lt.png'),
(108, 'Luxemburgo', 'Luxemburgo', 'https://flagpedia.net/data/flags/h80/lu.png'),
(109, 'Madagascar', 'Madagascar', 'https://flagpedia.net/data/flags/h80/mg.png'),
(110, 'Malasia', 'Malasia', 'https://flagpedia.net/data/flags/h80/my.png'),
(111, 'Malaui', 'Malaui', 'https://flagpedia.net/data/flags/h80/mw.png'),
(112, 'Maldivas', 'Maldivas', 'https://flagpedia.net/data/flags/h80/mv.png'),
(113, 'Malí', 'Malí', 'https://flagpedia.net/data/flags/h80/ml.png'),
(114, 'Malta', 'Malta', 'https://flagpedia.net/data/flags/h80/mt.png'),
(115, 'Marruecos', 'Marruecos', 'https://flagpedia.net/data/flags/h80/ma.png'),
(116, 'Mauricio', 'Mauricio', 'https://flagpedia.net/data/flags/h80/mu.png'),
(117, 'Mauritania', 'Mauritania', 'https://flagpedia.net/data/flags/h80/mr.png'),
(118, 'México', 'México', 'https://flagpedia.net/data/flags/h80/mx.png'),
(119, 'Micronesia', 'Micronesia', 'https://flagpedia.net/data/flags/h80/fm.png'),
(120, 'Moldavia', 'Moldavia', 'https://flagpedia.net/data/flags/h80/md.png'),
(121, 'Mónaco', 'Mónaco', 'https://flagpedia.net/data/flags/h80/mon.png'),
(122, 'Mongolia', 'Mongolia', 'https://flagpedia.net/data/flags/h80/mn.png'),
(123, 'Montenegro', 'Montenegro', 'https://flagpedia.net/data/flags/h80/me.png'),
(124, 'Mozambique', 'Mozambique', 'https://flagpedia.net/data/flags/h80/mz.png'),
(125, 'Namibia', 'Namibia', 'https://flagpedia.net/data/flags/h80/na.png'),
(126, 'Nauru', 'Nauru', 'https://flagpedia.net/data/flags/h80/nr.png'),
(127, 'Nepal', 'Nepal', 'https://flagpedia.net/data/flags/h80/np.png'),
(128, 'Nicaragua', 'Nicaragua', 'https://flagpedia.net/data/flags/h80/ni.png'),
(129, 'Níger', 'Níger', 'https://flagpedia.net/data/flags/h80/ne.png'),
(130, 'Nigeria', 'Nigeria', 'https://flagpedia.net/data/flags/h80/ng.png'),
(131, 'Niue', 'Niue', 'https://flagpedia.net/data/flags/h80/nu.png'),
(132, 'Noruega', 'Noruega', 'https://flagpedia.net/data/flags/h80/no.png'),
(133, 'Nueva Zelanda', 'Nueva Zelanda', 'https://flagpedia.net/data/flags/h80/nz.png'),
(134, 'Omán', 'Omán', 'https://flagpedia.net/data/flags/h80/om.png'),
(135, 'Países Bajos', 'Países Bajos', 'https://flagpedia.net/data/flags/h80/nl.png'),
(136, 'Pakistán', 'Pakistán', 'https://flagpedia.net/data/flags/h80/pk.png'),
(137, 'Palau', 'Palau', 'https://flagpedia.net/data/flags/h80/pw.png'),
(138, 'Panamá', 'Panamá', 'https://flagpedia.net/data/flags/h80/pa.png'),
(139, 'Papúa Nueva Guinea', 'Papúa Nueva Guinea', 'https://flagpedia.net/data/flags/h80/pg.png'),
(140, 'Paraguay', 'Paraguay', 'https://flagpedia.net/data/flags/h80/py.png'),
(141, 'Perú', 'Perú', 'https://flagpedia.net/data/flags/h80/pe.png'),
(142, 'Polonia', 'Polonia', 'https://flagpedia.net/data/flags/h80/pl.png'),
(143, 'Portugal', 'Portugal', 'https://flagpedia.net/data/flags/h80/pt.png'),
(144, 'Reino Unido', 'Reino Unido', 'https://flagpedia.net/data/flags/h80/gb.png'),
(145, 'República Checa', 'República Checa', 'https://flagpedia.net/data/flags/h80/cz.png'),
(146, 'República Dominicana', 'República Dominicana', 'https://flagpedia.net/data/flags/h80/do.png'),
(147, 'Ruanda', 'Ruanda', 'https://flagpedia.net/data/flags/h80/rw.png'),
(148, 'Rumanía', 'Rumanía', 'https://flagpedia.net/data/flags/h80/ro.png'),
(149, 'Rusia', 'Rusia', 'https://flagpedia.net/data/flags/h80/ru.png'),
(150, 'Sáhara Occidental', 'Sáhara Occidental', 'https://flagpedia.net/data/flags/h80/sd.png');
INSERT INTO equipos (id, nombre, pais, bandera_url) VALUES
(151, 'San Cristóbal y Nieves', 'San Cristóbal y Nieves', 'https://flagpedia.net/data/flags/h80/kn.png'),
(152, 'San Marino', 'San Marino', 'https://flagpedia.net/data/flags/h80/sm.png'),
(153, 'Santa Lucía', 'Santa Lucía', 'https://flagpedia.net/data/flags/h80/lc.png'),
(154, 'Santo Tomé y Príncipe', 'Santo Tomé y Príncipe', 'https://flagpedia.net/data/flags/h80/st.png'),
(155, 'Senegal', 'Senegal', 'https://flagpedia.net/data/flags/h80/sn.png'),
(156, 'Serbia', 'Serbia', 'https://flagpedia.net/data/flags/h80/rs.png'),
(157, 'Seychelles', 'Seychelles', 'https://flagpedia.net/data/flags/h80/sc.png'),
(158, 'Sierra Leona', 'Sierra Leona', 'https://flagpedia.net/data/flags/h80/sl.png'),
(159, 'Singapur', 'Singapur', 'https://flagpedia.net/data/flags/h80/sg.png'),
(160, 'Siria', 'Siria', 'https://flagpedia.net/data/flags/h80/sy.png'),
(161, 'Somalia', 'Somalia', 'https://flagpedia.net/data/flags/h80/so.png'),
(162, 'Sri Lanka', 'Sri Lanka', 'https://flagpedia.net/data/flags/h80/lk.png'),
(163, 'Suazilandia', 'Suazilandia', 'https://flagpedia.net/data/flags/h80/sz.png'),
(164, 'Sudán', 'Sudán', 'https://flagpedia.net/data/flags/h80/sd.png'),
(165, 'Sudán del Sur', 'Sudán del Sur', 'https://flagpedia.net/data/flags/h80/ss.png'),
(166, 'Suecia', 'Suecia', 'https://flagpedia.net/data/flags/h80/se.png'),
(167, 'Suiza', 'Suiza', 'https://flagpedia.net/data/flags/h80/ch.png'),
(168, 'Surinam', 'Surinam', 'https://flagpedia.net/data/flags/h80/sr.png'),
(169, 'Siria', 'Siria', 'https://flagpedia.net/data/flags/h80/sy.png'),
(170, 'Tailandia', 'Tailandia', 'https://flagpedia.net/data/flags/h80/th.png'),
(171, 'Tanzania', 'Tanzania', 'https://flagpedia.net/data/flags/h80/tz.png'),
(172, 'Togo', 'Togo', 'https://flagpedia.net/data/flags/h80/tg.png'),
(173, 'Tonga', 'Tonga', 'https://flagpedia.net/data/flags/h80/to.png'),
(174, 'Trinidad y Tobago', 'Trinidad y Tobago', 'https://flagpedia.net/data/flags/h80/tt.png'),
(175, 'Túnez', 'Túnez', 'https://flagpedia.net/data/flags/h80/tn.png'),
(176, 'Turkmenistán', 'Turkmenistán', 'https://flagpedia.net/data/flags/h80/tm.png'),
(177, 'Turquía', 'Turquía', 'https://flagpedia.net/data/flags/h80/tr.png'),
(178, 'Tuvalu', 'Tuvalu', 'https://flagpedia.net/data/flags/h80/tv.png'),
(179, 'Ucrania', 'Ucrania', 'https://flagpedia.net/data/flags/h80/ua.png'),
(180, 'Uganda', 'Uganda', 'https://flagpedia.net/data/flags/h80/ug.png'),
(181, 'Uruguay', 'Uruguay', 'https://flagpedia.net/data/flags/h80/uy.png'),
(182, 'Uzbekistán', 'Uzbekistán', 'https://flagpedia.net/data/flags/h80/uz.png'),
(183, 'Vanuatu', 'Vanuatu', 'https://flagpedia.net/data/flags/h80/vu.png'),
(184, 'Vaticano', 'Vaticano', 'https://flagpedia.net/data/flags/h80/va.png'),
(185, 'Venezuela', 'Venezuela', 'https://flagpedia.net/data/flags/h80/ve.png'),
(186, 'Vietnam', 'Vietnam', 'https://flagpedia.net/data/flags/h80/vn.png'),
(187, 'Yemen', 'Yemen', 'https://flagpedia.net/data/flags/h80/ye.png'),
(188, 'Yibuti', 'Yibuti', 'https://flagpedia.net/data/flags/h80/dj.png'),
(189, 'Zambia', 'Zambia', 'https://flagpedia.net/data/flags/h80/zm.png'),
(190, 'Zimbabue', 'Zimbabue', 'https://flagpedia.net/data/flags/h80/zw.png');